name: install-nodejs
description: Install
source: github.com/bharath92/pipelines-task-hello-world
labels:
  - nodejs
input:
  - name: version
    description: Version of nodejs to be installed.
execution:
  - curl -fsSL https://rpm.nodesource.com/setup_$IN_version.x | sudo bash -