name: install-nodejs
description: Install
source: github.com/bharath92/pipelines-task-hello-world
labels:
  - nodejs
input:
  - name: version
    description: Version of nodejs to be installed.
execution:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
  - nvm install $version
  - nvm use $version